name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - "clang_tools/*"
      - "tests/*"
      - "**requirements*.txt"
      - pyproject.toml
      - .pre-commit-config.yaml
      - ".github/workflows/python-test.yml"
      - "!docs/**"
  workflow_dispatch:


jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5

      - name: Set up Python 3.10
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install .[dev]

      - name: Collect Coverage
        run: coverage run -m pytest -vv

      - name: Upload coverage data
        uses: actions/upload-artifact@v5
        with:
          name: coverage-data-${{ runner.os }}
          path: .coverage*
          include-hidden-files: true

  coverage-report:
    needs: [test]
    uses: cpp-linter/.github/.github/workflows/py-coverage.yml@main
    secrets: inherit

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.10
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v5
        with:
          python-version: "3.10"

      - name: Build wheel
        run: python -m pip wheel -w dist .

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 #v4
        with:
          name: clang-tools-pip_wheel
          path: dist/clang_tools*.whl

  install:
    needs: [build]
    strategy:
      matrix:
        version: [ 9, 10, 11, 12, 12.0.1, 13, 14, 15, 16, 17, 18, 19, 20, 21 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v5
        with:
          python-version: "3.10"

      - name: Download wheel artifact
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: clang-tools-pip_wheel
          path: dist/

      - name: Install pkg from wheel
        # using a wildcard as filename on Windows requires a bash shell
        shell: bash
        run: pip install dist/*.whl

      - name: Install clang-tools binaries
        run: clang-tools --install ${{ matrix.version }} --tool clang-format clang-tidy clang-query clang-apply-replacements

      - name: Show path of clang-tools binaries
        shell: bash
        run: |
          if [ "${{ matrix.version }}" = "15" -o "${{ matrix.version }}" = "16" ] && [ "${{ matrix.os }}" = "windows-latest" ]; then
              which clang-format
              which clang-tidy
              which clang-query
              which clang-apply-replacements
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
              which "clang-format-${{ matrix.version }}"
              which "clang-tidy-${{ matrix.version }}"
              which "clang-query-${{ matrix.version }}"
              which "clang-apply-replacements-${{ matrix.version }}"
          fi

      - name: Check clang-tools binaries on Windows
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          case "${{ matrix.version }}" in
            15|16|18|20|21)
              clang-format.exe --version
              clang-tidy.exe --version
              clang-query.exe --version
              clang-apply-replacements.exe --version
              ;;
            *)
              clang-format-${{ matrix.version }}.exe --version
              clang-tidy-${{ matrix.version }}.exe --version
              clang-query-${{ matrix.version }}.exe --version
              clang-apply-replacements-${{ matrix.version }}.exe --version
              ;;
          esac

      - name: Check clang-tools binaries on Unix
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          if [ "${{ matrix.version }}" = "12.0.1" -a "${{ matrix.os }}" = "ubuntu-latest" ]; then
            clang-format-12.0.1 --version
            clang-tidy-12.0.1 --version
            clang-query-12.0.1 --version
            clang-apply-replacements-12.0.1 --version
          else
            clang-format-${{ matrix.version }} --version
            clang-tidy-${{ matrix.version }} --version
            clang-query-${{ matrix.version }} --version
            clang-apply-replacements-${{ matrix.version }} --version
          fi

      - name: Install and check clang-format wheels
        if: ${{ matrix.version != '12.0.1' && fromJSON(matrix.version) >= 10 }} # Skip 12.0.1
        shell: bash
        run: |
          set -e
          clang-tools-wheel --tool clang-format --version ${{ matrix.version }}

          echo "Checking clang-format versions..."
          clang-format --version

          # Verify versions contain expected string
          clang_format_version=$(clang-format --version)

          echo "clang-format version: $clang_format_version"

          if ! echo "$clang_format_version" | grep -q "version ${{ matrix.version }}"; then
            echo "❌ Unexpected clang-format version!"
            exit 1
          fi

          echo "✅ clang-format Versions are correct."

      - name: Install and check clang-tidy wheels
        if: ${{ matrix.version != '12.0.1' && fromJSON(matrix.version) >= 13 }}
        shell: bash
        run: |
          set -e
          clang-tools-wheel --tool clang-tidy --version ${{ matrix.version }}

          echo "Checking clang-tidy versions..."
          clang-tidy --version

          # Verify versions contain expected string
          clang_tidy_version=$(clang-tidy --version)

          echo "clang-tidy version: $clang_tidy_version"

          if ! echo "$clang_tidy_version" | grep -q "version ${{ matrix.version }}"; then
            echo "❌ Unexpected clang-tidy version!"
            exit 1
          fi

          echo "✅ clang-tidy Versions are correct."

  docs:
    uses: cpp-linter/.github/.github/workflows/sphinx.yml@main
    with:
      path-to-doc: docs/_build/html
